name: shamba
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  action_slider: ^0.7.0
  auto_route: ^10.0.1
  bloc: ^8.1.4
  bottom_sheet: ^4.0.4
  bottom_sheet_bar: ^2.3.10
  camerawesome: ^2.3.0
  collection: ^1.19.1
  dartz: ^0.10.1
  dotted_border: ^2.1.0
  flex_seed_scheme: ^3.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gemini: ^3.0.0
  flutter_heatmap_calendar: ^1.0.5
  flutter_hicons: ^1.0.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  flutter_native_splash: ^2.4.6
  get_it: ^8.0.3
  glass_kit: ^4.0.1
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.7
  heroicons: ^0.11.0
  hydrated_bloc: ^9.1.5
  iconly: ^1.0.1
  image_picker: ^1.1.2
  image_stack: ^2.1.1
  intl: ^0.19.0
  modal_bottom_sheet: ^3.0.0
  palette_generator: ^0.3.3+7
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  pinput: ^5.0.1
  shadow_overlay: ^1.0.5
  swipe_refresh: ^1.1.2
  syncfusion_flutter_charts: ^29.1.41
  syncfusion_flutter_gauges: ^29.1.40
  url_launcher: ^6.3.1

dev_dependencies:
  auto_route_generator: ^10.0.1
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  fast_i18n: ^5.12.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
